[build-system]
requires = ["setuptools>=60", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "redbb"
authors = [
    { name = "João Severo", email = "contato@gmail.com" }
]
description = "Asynchronous MongoDB Driver Wrapper For Rust MongoDB crate"
readme = "README.md"
requires-python= ">=3.11"
keywords = ["rust", "mongo", "driver", "database"]
dynamic = ["version"]
