from .database import Database
from .session import Session

class Client:
    def database(self, database_name: str) -> Database: ...
    def default_database(self) -> Database | None: ...
    async def list_databases(self) -> list[str]: ...
    async def create_session(self) -> Session: ...
    async def shutdown(self) -> None: ...

async def create_client(db_uri: str) -> Client: ...
