from .collection import Collection

class Database:
    def collection(self, collection_name: str) -> Collection: ...
    async def list_collections(self) -> list[str]: ...
    async def drop(self) -> None: ...
