name: "Test"

on:
    push:
        branches-ignore:
            - "master"
        tags-ignore:
            - "**"
        paths:
            - "ruson/**"
            - "src/**"
            - ".github/**"
    workflow_dispatch:

jobs:
    checkout:
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

    python-check:
        name: Static code check
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: Install code check dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install black isort

            - name: "Check with <black>"
              run: black --check ruson

            - name: "Check with <isort>"
              run: isort --profile black --check ruson

    test:
        name: Test Ruson
        needs: python-check, checkout
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: pip install .

            - name: Test
              run: pytest . --disable-warnings
